# nixpacks.toml - Railway deployment configuration
# This file tells Railway's Nixpacks to include ffmpeg system dependency

[phases.setup]
nixPkgs = ["...", "ffmpeg-full"]

# Alternative approach - use apt packages if nixpkgs doesn't work
[phases.build]
aptPkgs = ["ffmpeg"]