[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "cd client && npm ci",
    "cd server && npm ci"
]

[phases.build]
cmds = [
    "cd client && npm run build",
    "cp -r client/dist server/client-dist"
]

[start]
cmd = "cd server && node server.js"