[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[variables]
NODE_OPTIONS = "--max-old-space-size=2048"
NPM_CONFIG_MAXSOCKETS = "1"

[phases.install]
cmds = [
    "cd client && npm ci --no-audit --no-fund",
    "cd server && npm ci --omit=dev --no-audit --no-fund"
]

[phases.build]
cmds = [
    "cd client && NODE_OPTIONS='--max-old-space-size=2048' npm run build",
    "cp -r client/dist server/client-dist"
]

[start]
cmd = "cd server && node server.js"