[build]
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
[services.variables]
NODE_ENV = "production"
PORT = "3001"

[services.healthcheck]
path = "/health"
interval = 30
timeout = 10
retries = 3

[services.resources]
replicas = 1
cpuType = "SHARED"
memory = "512MB"